// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVIclrwhn5lxUVWPqxBD2kc7InrhEkaMg',
    appId: '1:456399202558:web:8556c44d9b78f922fe5daf',
    messagingSenderId: '456399202558',
    projectId: 'we-chat-97e31',
    authDomain: 'we-chat-97e31.firebaseapp.com',
    storageBucket: 'we-chat-97e31.firebasestorage.app',
    measurementId: 'G-KYH9PZJ9Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1VKGcrwtmdjxKUhmjr2ASOIlBvNwhXY0',
    appId: '1:456399202558:android:166ccdb65bcaa1b5fe5daf',
    messagingSenderId: '456399202558',
    projectId: 'we-chat-97e31',
    storageBucket: 'we-chat-97e31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS_TT7NP_fKAFmgtG4mzd4-j6b335Dmqk',
    appId: '1:456399202558:ios:2276db17cb975957fe5daf',
    messagingSenderId: '456399202558',
    projectId: 'we-chat-97e31',
    storageBucket: 'we-chat-97e31.firebasestorage.app',
    androidClientId: '456399202558-cna2ul490iirh348ll20v4k9mgv0ug92.apps.googleusercontent.com',
    iosClientId: '456399202558-pbnl26c2b8rm087rjkprt25r45rm1r9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS_TT7NP_fKAFmgtG4mzd4-j6b335Dmqk',
    appId: '1:456399202558:ios:2276db17cb975957fe5daf',
    messagingSenderId: '456399202558',
    projectId: 'we-chat-97e31',
    storageBucket: 'we-chat-97e31.firebasestorage.app',
    androidClientId: '456399202558-cna2ul490iirh348ll20v4k9mgv0ug92.apps.googleusercontent.com',
    iosClientId: '456399202558-pbnl26c2b8rm087rjkprt25r45rm1r9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVIclrwhn5lxUVWPqxBD2kc7InrhEkaMg',
    appId: '1:456399202558:web:92c2b05308760b65fe5daf',
    messagingSenderId: '456399202558',
    projectId: 'we-chat-97e31',
    authDomain: 'we-chat-97e31.firebaseapp.com',
    storageBucket: 'we-chat-97e31.firebasestorage.app',
    measurementId: 'G-9FR7D32Z64',
  );

}